export const APICIL_PAYS = {
    AF: "AFGHANISTAN",
    ZA: "AFRIQUE DU SUD",
    AL: "ALBANIE",
    DZ: "ALGERIE",
    DE: "ALLEMAGNE",
    AD: "ANDORRE",
    AO: "ANGOLA",
    AG: "ANTIGUA-ET-BARBUDA",
    AN: "ANTILLES NEERLANDAISES",
    SA: "ARABIE SAOUDITE",
    AR: "ARGENTINE",
    AM: "ARMENIE",
    AU: "AUSTRALIE",
    AT: "AUTRICHE",
    AZ: "AZERBAIDJAN",
    BS: "BAHAMAS",
    BH: "BAHREIN",
    BD: "BANGLADESH",
    BB: "BARBADE",
    BE: "BELGIQUE",
    BZ: "BELIZE",
    BJ: "BENIN",
    BT: "BHOUTAN",
    BY: "BIELORUSSIE",
    MM: "BIRMANIE",
    BO: "BOLIVIE",
    BQ: "BONAIRE, SAINT EUSTACHE ET SABA",
    BA: "BOSNIE-HERZEGOVINE",
    BW: "BOTSWANA",
    BR: "BRESIL",
    BN: "BRUNEI",
    BG: "BULGARIE",
    BF: "BURKINA",
    BI: "BURUNDI",
    KY: "CAIMANES (ILES)",
    KH: "CAMBODGE",
    CM: "CAMEROUN",
    CA: "CANADA",
    CV: "CAP-VERT",
    CF: "CENTRAFRICAINE (REPUBLIQUE)",
    CL: "CHILI",
    CN: "CHINE",
    CY: "CHYPRE",
    CO: "COLOMBIE",
    KM: "COMORES",
    CG: "CONGO",
    CD: "CONGO (REPUBLIQUE DEMOCRATIQUE)",
    CK: "COOK (ILES)",
    KR: "COREE (REPUBLIQUE DE)",
    KP: "COREE (REPUBLIQUE POPULAIRE DEMOCRATIQUE DE)",
    CR: "COSTA RICA",
    CI: "COTE D'IVOIRE",
    HR: "CROATIE",
    CU: "CUBA",
    CW: "CURAÇAO",
    DK: "DANEMARK",
    DJ: "DJIBOUTI",
    DO: "DOMINICAINE (REPUBLIQUE)",
    DM: "DOMINIQUE",
    EG: "EGYPTE",
    SV: "EL SALVADOR",
    AE: "EMIRATS ARABES UNIS",
    EC: "EQUATEUR",
    ER: "ERYTHREE",
    ES: "ESPAGNE",
    EE: "ESTONIE",
    SZ: "ESWATINI",
    US: "ETATS-UNIS",
    ET: "ETHIOPIE",
    MK: "EX-REPUBLIQUE YOUGOSLAVE DE MACEDOINE",
    FO: "FEROE (ILES)",
    FJ: "FIDJI",
    FI: "FINLANDE",
    FR: "FRANCE",
    GA: "GABON",
    GM: "GAMBIE",
    GE: "GEORGIE",
    GH: "GHANA",
    GI: "GIBRALTAR",
    GR: "GRECE",
    GD: "GRENADE",
    GL: "GROENLAND",
    GT: "GUATEMALA",
    GG: "GUERNESEY",
    GN: "GUINEE",
    GQ: "GUINEE EQUATORIALE",
    GW: "GUINEE-BISSAU",
    GY: "GUYANA",
    HT: "HAITI",
    HN: "HONDURAS",
    HK: "HONG-KONG",
    HU: "HONGRIE",
    IN: "INDE",
    ID: "INDONESIE",
    IR: "IRAN",
    IQ: "IRAQ",
    IE: "IRLANDE, ou EIRE",
    IS: "ISLANDE",
    IL: "ISRAEL",
    IT: "ITALIE",
    JM: "JAMAIQUE",
    JP: "JAPON",
    JE: "JERSEY",
    JO: "JORDANIE",
    KZ: "KAZAKHSTAN",
    KE: "KENYA",
    KG: "KIRGHIZISTAN",
    KI: "KIRIBATI",
    XK: "KOSOVO",
    KW: "KOWEIT",
    LA: "LAOS",
    LS: "LESOTHO",
    LV: "LETTONIE",
    LB: "Liban",
    LR: "LIBERIA",
    LY: "LIBYE",
    LI: "LIECHTENSTEIN",
    LT: "LITUANIE",
    LU: "LUXEMBOURG",
    MO: "MACAO",
    MG: "MADAGASCAR",
    MY: "MALAISIE",
    MW: "MALAWI",
    MV: "MALDIVES",
    ML: "MALI",
    MT: "MALTE",
    IM: "MAN (ILE)",
    MA: "MAROC",
    MH: "MARSHALL (ILES)",
    MU: "MAURICE",
    MR: "MAURITANIE",
    MX: "MEXIQUE",
    FM: "MICRONESIE (ETATS FEDERES DE)",
    MD: "MOLDAVIE",
    MC: "MONACO",
    MN: "MONGOLIE",
    ME: "MONTENEGRO",
    MZ: "MOZAMBIQUE",
    NA: "NAMIBIE",
    NR: "NAURU",
    NP: "NEPAL",
    NI: "NICARAGUA",
    NE: "NIGER",
    NG: "NIGERIA",
    NO: "NORVEGE",
    NZ: "NOUVELLE-ZELANDE",
    IO: "OCEAN INDIEN (TERRITOIRE BRITANNIQUE DE L')",
    OM: "OMAN",
    UG: "OUGANDA",
    UZ: "OUZBEKISTAN",
    PK: "PAKISTAN",
    PW: "PALAOS (ILES)",
    PS: "PALESTINE (Etat de)",
    PA: "PANAMA",
    PG: "PAPOUASIE-NOUVELLE-GUINEE",
    PY: "PARAGUAY",
    NL: "PAYS-BAS",
    PE: "PEROU",
    PH: "PHILIPPINES",
    PN: "PITCAIRN (ILE)",
    PL: "POLOGNE",
    PT: "PORTUGAL",
    QA: "QATAR",
    RO: "ROUMANIE",
    GB: "ROYAUME-UNI",
    RU: "RUSSIE",
    RW: "RWANDA",
    EH: "SAHARA OCCIDENTAL",
    KN: "SAINT-CHRISTOPHE-ET-NIEVES",
    SM: "SAINT-MARIN",
    SX: "SAINT-MARTIN (PARTIE NEERLANDAISE)",
    VC: "SAINT-VINCENT-ET-LES GRENADINES",
    SH: "SAINTE HELENE, ASCENSION ET TRISTAN DA CUNHA",
    LC: "SAINTE-LUCIE",
    Sb: "SALOMON (ILES)",
    WS: "SAMOA OCCIDENTALES",
    ST: "SAO TOME-ET-PRINCIPE",
    SN: "SENEGAL",
    RS: "SERBIE",
    SC: "SEYCHELLES",
    SL: "SIERRA LEONE",
    SG: "SINGAPOUR",
    SK: "SLOVAQUIE",
    SI: "SLOVENIE",
    SO: "SOMALIE",
    SD: "SOUDAN",
    SS: "SOUDAN DU SUD",
    LK: "SRI LANKA",
    SE: "SUEDE",
    CH: "SUISSE",
    SR: "SURINAME",
    SY: "SYRIE",
    TJ: "TADJIKISTAN",
    TW: "TAIWAN",
    TZ: "TANZANIE",
    TD: "TCHAD",
    CZ: "TCHEQUE (REPUBLIQUE)",
    TH: "THAILANDE",
    TL: "TIMOR ORIENTAL",
    TG: "TOGO",
    TO: "TONGA",
    TT: "TRINITE-ET-TOBAGO",
    TN: "TUNISIE",
    TM: "TURKMENISTAN",
    TR: "TURQUIE",
    TV: "TUVALU",
    UA: "UKRAINE",
    UY: "URUGUAY",
    VU: "VANUATU",
    VA: "VATICAN, ou SAINT-SIEGE",
    VE: "VENEZUELA",
    VN: "VIET NAM",
    YE: "YEMEN",
    ZM: "ZAMBIE",
    ZW: "ZIMBABWE",
};

export const APICIL_NATIONALITE = {
    AF: "Afghane",
    AL: "Albanaise",
    DZ: "Algérienne",
    DE: "Allemande",
    US: "Américaine",
    AD: "Andorrane",
    AO: "Angolaise",
    AG: "Antiguayenne",
    AN: "Antillaise (Antilles Néerlandaise)",
    AR: "Argentine",
    AM: "Arménienne",
    AU: "Australienne",
    AT: "Autrichienne",
    AZ: "Azerbaïdjanaise",
    BS: "Bahamienne",
    BH: "Bahreïnienne",
    BD: "Bangladaise",
    BB: "Barbadienne",
    BE: "Belge",
    BZ: "Bélizienne",
    BJ: "Béninoise",
    BM: "Bermudes",
    BT: "Bhoutanaise",
    BY: "Biélorusse",
    MM: "Birmane",
    GW: "Bissau-Guinéenne",
    BO: "Bolivienne",
    BA: "Bosnienne",
    BW: "Botswanaise",
    BR: "Brésilienne",
    GB: "Britannique",
    BN: "Brunéienne",
    BG: "Bulgare",
    BF: "Burkinabé",
    BI: "Burundaise",
    KY: "CAIMANES (ILES)",
    KH: "Cambodgienne",
    CM: "Camerounaise",
    CA: "Canadienne",
    CV: "Cap-verdienne",
    CF: "Centrafricaine",
    CL: "Chilienne",
    CN: "Chinoise",
    KN: "Christophienne",
    CY: "Chypriote",
    CO: "Colombienne",
    KM: "Comorienne",
    CG: "Congolaise",
    CD: "Congolaise (RDC)",
    CK: "Cookienne",
    CR: "Costaricaine",
    HR: "Croate",
    CU: "Cubaine",
    DK: "Danoise",
    DJ: "Djiboutienne",
    DO: "Dominicaine",
    DM: "Dominiquaise",
    EG: "Egyptienne",
    AE: "Emirienne",
    GQ: "Equato-Guinéenne",
    EC: "Equatorienne",
    ER: "Erythréenne",
    ES: "Espagnole",
    EE: "Estonienne",
    SZ: "Eswatinienne",
    ET: "Ethiopienne",
    FO: "FEROE (ILES)",
    FJ: "Fidjienne",
    FI: "Finlandaise",
    FR: "Française",
    GA: "Gabonaise",
    GM: "Gambienne",
    GE: "Georgienne",
    GH: "Ghanéenne",
    GI: "Gibraltar",
    GD: "Grenadienne",
    GL: "GROENLAND",
    GP: "Guadeloupe",
    GT: "Guatémaltèque",
    GG: "Guernesiaise",
    GN: "Guinéenne",
    GY: "Guyana",
    GF: "GUYANE",
    HT: "Haïtienne",
    GR: "Hellénique",
    HN: "Hondurienne",
    HK: "Hong Kong",
    HU: "Hongroise",
    IN: "Indienne",
    ID: "Indonésienne",
    IQ: "Irakienne",
    IR: "Iranien",
    IE: "Irlandaise",
    IS: "Islandaise",
    IL: "Israélienne",
    IT: "Italienne",
    CI: "Ivoirienne",
    JM: "Jamaïcaine",
    JP: "Japonaise",
    JE: "JERSEY",
    JO: "Jordanienne",
    KZ: "Kazakhstanaise",
    KE: "Kenyane",
    KG: "Kirghize",
    KI: "Kiribatienne",
    XK: "Kosovare",
    KW: "Koweitienne",
    X1: "LA REUNION",
    LA: "Laotienne",
    LS: "Lesothane",
    LV: "Lettone",
    LB: "Libanaise",
    LR: "Libérienne",
    LY: "Libyenne",
    LI: "Liechtensteinoise",
    LT: "Lituanienne",
    LU: "Luxembourgeoise",
    MO: "Macao",
    MK: "Macédonienne",
    MY: "Malaisienne",
    MW: "Malawienne",
    MV: "Maldivienne",
    MG: "Malgache",
    ML: "Malienne",
    MT: "Maltaise",
    IM: "MAN (ILE)",
    MA: "Marocaine",
    MH: "Marshallaise",
    MQ: "Martinique",
    MU: "Mauricienne",
    MR: "Mauritanienne",
    YT: "MAYOTTE",
    MX: "Mexicaine",
    FM: "Micronésienne",
    MD: "Moldave",
    MC: "Monégasque",
    MN: "Mongole",
    ME: "Monténégrine",
    MS: "Montserrat",
    MZ: "Mozambicaine",
    NA: "Namibienne",
    NR: "Nauruane",
    NL: "Néerlandaise",
    NZ: "Néo-zélandaise",
    NP: "Népalaise",
    NI: "Nicaraguayenne",
    NE: "Niger",
    NG: "Nigériane",
    KP: "Nord-coréenne",
    NO: "Norvégienne",
    NC: "Nouvelle Calédonie",
    IO: "OCEAN INDIEN (TERRITOIRE BRITANNIQUE DE L')",
    OM: "Omanaise",
    UG: "Ougandaise",
    UZ: "Ouzbèke",
    PK: "Pakistanaise",
    PW: "Palaoise",
    PS: "Palestinien",
    PA: "Panaméenne",
    PG: "Papouasienne",
    PY: "Paraguayenne",
    PE: "Péruvienne",
    PH: "Philippine",
    PN: "PITCAIRN (ILE)",
    PL: "Polonaise",
    PF: "Polynésie Française",
    PT: "Portuguaise",
    QA: "Qatarienne",
    RO: "Roumaine",
    RU: "Russe",
    RW: "Rwandaise",
    BL: "SAINT-BARTHELEMY",
    LC: "Saint-Lucienne",
    SM: "Saint-Marinaise",
    MF: "SAINT-MARTIN",
    PM: "SAINT-PIERRE-ET-MIQUELON",
    SH: "SAINTE HELENE, ASCENSION ET TRISTAN DA CUNHA",
    SB: "Salomonaise",
    SV: "Salvadorienne",
    WS: "Samoane",
    ST: "Santoméenne",
    SA: "Saoudienne",
    SN: "Sénégalaise",
    RS: "Serbe",
    SC: "Seychelloise",
    SL: "Sierraléonaise",
    SG: "Singapourienne",
    SK: "Slovaque",
    SI: "Slovène",
    SO: "Somalienne",
    SD: "Soudanaise",
    LK: "Sri-lankaise",
    ZA: "Sud-africaine",
    KR: "Sud-coréenne",
    SS: "Sud-soudanaise",
    SE: "Suédoise",
    CH: "Suisse",
    SR: "Surinamaise",
    SY: "Syrienne",
    TJ: "Tadjike",
    TW: "Taiwanaise",
    TZ: "Tanzanienne",
    TD: "Tchadienne",
    CZ: "Tchèque",
    TF: "TERRES AUSTRALES FRANCAISES",
    TH: "Thaïlandaise",
    TL: "Timoraise",
    TO: "Tonga",
    TG: "Tonguienne",
    TT: "Trinidadienne",
    TN: "Tunisienne",
    TM: "Turkmène",
    TR: "Turque",
    TV: "Tuvalaise",
    UA: "Ukrainienne",
    UY: "Uruguayenne",
    VU: "Vanuatuane",
    VA: "Vaticanaise",
    VE: "Vénézuélienne",
    VN: "Vietnamienne",
    VC: "Vincentaise",
    WF: "WALLIS-ET-FUTUNA",
    YE: "Yéménite",
    ZM: "Zambienne",
    ZW: "Zimbabwéenne",
};
